create database kiwify
create table if not exists users
(
    id          integer generated by default as identity
        primary key,
    "fullName"  varchar,
    email       varchar,
    password    varchar,
    "createdAt" timestamp,
    "isTutor"   boolean,
    "updatedAt" date
);

alter table users
owner to postgres;

create table if not exists quiz
(
    id          integer generated by default as identity
        primary key,
    title       varchar,
    description text,
    "createdOn" date,
    "updatedOn" date,
    "createdBy" integer
        references users,
    "isDeleted" boolean,
    "isActive"  boolean
);

alter table quiz
    owner to postgres;

create table if not exists questions
(
    id              integer generated by default as identity
        primary key,
    "quizId"        integer
        references quiz,
    title           varchar,
    "answerType"    boolean,
    choices         json,
    "correctAnswer" json,
    "isMandatory"   boolean,
    "createdOn"     date,
    "updatedOn"     date,
    "isActive"      boolean,
    "isDeleted"     boolean
);

alter table questions
    owner to postgres;

create table if not exists attempts
(
    id            integer generated by default as identity
        primary key,
    "userId"      integer,
    rating        integer,
    "quizId"      integer
        references quiz,
    result        integer,
    outof         integer,
    "createdOn"   date,
    "completedOn" date
);

alter table attempts
    owner to postgres;

create table if not exists answers
(
    id           integer generated by default as identity
        primary key,
    "attemptId"  integer
        references attempts,
    "questionId" integer
        references questions,
    answer       json,
    "isCorrect"  boolean
);

alter table answers
    owner to postgres;